config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'home#home'
  
  resources :variants, :path => "produits" do 
    resources :reviews
  end
  resources :wishlists, :path => "ma_wishlist"

  resources :orders, :path => "mes_commandes"
  resources :items
  resources :options
  resources :option_values
  resources :option_associations

  resources :searches, :path => "recherches"
  
  devise_for :users,
    controllers: { registrations: 'registrations' },
    path: '',
    path_names: { sign_up: 'creer_un_compte', sign_in: 'identification', sign_out: 'deconnexion', password: 'mot_de_passe_oublie'}
  devise_scope :user do 
    get "/mon_profil" => "registrations#show"
  end
  
  get '/carts/payment' => 'carts#payment'
  resources :carts, :path => "mon_panier"
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'
  resources :posts, :path => "blog"
  get "/postDashboard", to: "posts#postDashboard"

  get '/home/about_us', to: 'home#about_us', as: 'a_propos'
  get "/home/contact", to: "home#contact", as: 'contact'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :variant
  belongs_to :user

  validates :quantity,
    presence: true, 
    numericality: { only_integer: true, greater_than: 0 }

  def total_per_item
    return self.quantity.to_f * Variant.find_by_id(self.variant_id).price.to_f
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:update, :destroy, :additem, :removeitem]
  before_action :authenticate_user!

  def index
    @carts = Cart.where(user_id: current_user.id).where(order_id: nil).order(:id)
    @carts.empty? ? countCart = 0 : countCart = @carts.size 
    @amount = @carts.map(&:total_per_item).instance_eval { reduce(:+) }

    if @carts.empty?
      flash.now[:alert] = "Votre panier est vide"
    end
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.user_id = current_user.id

    respond_to do |format|
      if @cart.save
        format.html { redirect_to request.referer, notice: "L'article a été rajouté au panier" }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to request.referer, notice: 'Le panier a été mis à jour avec succès' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: "L'article a été retiré du panier" }
      format.json { head :no_content }
    end
  end

  def additem
    @qty = @cart.quantity
    if @qty < Variant.find(@cart.variant_id).stock
      @qty += 1
      @cart.update(quantity: @qty)
      respond_to do |format|
        format.html { redirect_to request.referer, notice: 'Le panier a été mis à jour avec succès' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to request.referer, alert: "Le revendeur ne possède que #{Variant.find(@cart.variant_id).stock} exemplaire(s) de cet article en stock" }
        format.json { head :no_content }
      end
    end
  end

  def removeitem
    @qty = @cart.quantity - 1
    @cart.update(quantity: @qty)
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Le panier a été mis à jour avec succès' }
      format.json { head :no_content }
    end
  end

  def payment
    if params[:country].blank? then
      order_params = params.permit(:address, :zipcode)
    else
      order_params = params.permit(:address, :zipcode, :country)
    end

    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @carts = Cart.where(user_id: current_user.id).where(order_id: nil)
    @amount = ((@carts.map(&:total_per_item).instance_eval { reduce(:+) })*100).to_i

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      #description renvoie a quel nom est cree le compte (details des payments visibles sur stripe directement, notament le nom)
      description: 'Rails Stripe customer',
      currency: 'EUR',
    })

    @order.stripe_id = params[:stripeToken]

    @order.save
    @carts.each do |item_in_cart|
        v = Variant.find(item_in_cart.variant_id)
        item_in_cart.update(order_id: @order.id)
        v.update(stock: v.stock - item_in_cart.quantity)
    end   

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :root
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:order_id, :variant_id, :quantity)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="table table-borderless table-cart" data-addclass-on-smdown="table-sm">
  <tbody>
  <% carts.order(:id).each do |cart| %>        
    <tr>
      <td class="cart-img nostretch">
        <%= link_to image_tag("item.jpg"), variant_path(Variant.find(cart.variant_id)) %>
      </td>
      <td class="cart-title">
        <%= link_to cart.variant.title, variant_path(Variant.find(cart.variant_id)), class: "h6 bold d-inline-block", title: cart.variant.title  %>
        <% if Variant.find(cart.variant_id).stock == 0 %>
          <div><span class="text-danger"><i class="fas fa-times-circle"></i></span> Indisponible</div> 
        <% else %>
          <div><span class="text-success"><i class="fas fa-check-circle"></i></span> Disponible </div>
        <% end %>
        <small><b>Prix</b>: <%= cart.variant.price%> €</small>
        
      </td>
      <td class="cart-qty nostretch text-center">
        <div class="spinner" data-addclass-on-smdown="spinner-sm wrap">
          <% if cart.quantity == 1 %>
            <%= link_to cart, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-icon rounded-circle" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% else %>
            <%= link_to removefromcart_path(cart.id), method: "get", class: "btn btn-icon rounded-circle" do %>
              <i class="fas fa-minus"></i>
            <% end %>
          <% end %>
          <input type="number" class="form-control" value="<%= cart.quantity %>" min="1" max="999">
          <%= link_to addtocart_path(cart.id), method: "get", class: "btn btn-icon rounded-circle" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </div>
      </td>
      <td class="cart-price text-right">
        <span class="roboto-condensed bold"><% subtotal = cart.quantity*cart.variant.price %><%= subtotal %>€</span>
      </td>
      <td class="cart-action nostretch pr-0">
        <div class="dropdown">
          <%= link_to "javascript:void(0)", :class => "nav-icon text-secondary dropdown-toggle", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
            <i class="fas fa-angle-down"></i>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item text collapse" style="text-decoration:none;" type="button"><i class="fas fa-heart"></i> <%= link_to 'Plus tard (wishlist)', wishlists_path(user_id: cart.user.id, variant_id: cart.variant.id), method: :create %></button>
            <button class="dropdown-item text-danger" type="button"> <i class="fas fa-times"></i> <%= link_to 'Enlever', cart, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "text-danger" %></button>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
      
  </tbody>
</table>
<div class="text-center">
  <small class="counter">TOTAL</small>
  <h3 class="roboto-condensed bold"><%= total %> €</h3>
  <a id="btn_shipping" class="btn btn-primary rounded-pill btn-lg text-white"><i class="fas fa-long-arrow-alt-right"></i> LIVRAISON</a>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :variant_id %>
    <%= form.text_field :variant_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_shipping.html.erb
<div class="card-body pt-5 flex-center flex-column">
  <%= form_with(model: order, url: carts_payment_path, method: :get,  class: "form-checkout form-style-1") do |form| %>
    <div class="form-row">
      <div class="form-group col-12">
        <label for="shippingAddress">Adresse</label>
        <%= form.text_field :address, autofocus: true, autocomplete: "address", class: "form-control", placeholder: "", :required => true %>
      </div>
      <div class="form-group col-6 col-sm-6">
        <label for="shippingCountry">Code Postal</label>
        <%= form.text_field :zipcode, autofocus: true, autocomplete: "zipcode", class: "form-control", placeholder: "", :required => true %>
      </div>
      <div class="form-group col-6 col-sm-6">
        <label for="shippingCity">Pays</label>
        <%= form.text_field :country, autofocus: true, autocomplete: "country", class: "form-control", placeholder: "France" %>
      </div>
    </div>
    <hr>

    <div class="text-center">
      <small class="counter">TOTAL</small>
      <h3 class="roboto-condensed bold"><%= total %> €</h3>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span></span>
        </label>
      </article>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Nativea"
        data-label="Paiement"
        data-amount= total
        data-locale="auto">
      </script>
      <script>document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';</script>
      <button type="submit" class="btn btn-primary rounded-pill btn-lg"><i class="fas fa-long-arrow-alt-right"></i> Paiement</button>
    </div>
  <% end %>
</div>

app/views/carts/edit.html.erb
<h1>Edition du Panier</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Détail', @cart %> |
<%= link_to 'Retour', carts_path %>

app/views/carts/index.html.erb
<div class="container my-3">
  <div class="card">
    <div class="card-header bg-white border-bottom flex-center p-0">
      <ul class="nav nav-pills card-header-pills main-nav-pills" role="tablist">
        <li class="nav-item">
          <%= link_to "PANIER", "javascript:void(0)", id: "cart", :class => "nav-link disabled active", :data => {:toggle => "tab"}, :role =>'tab', :aria => {:controls => "cart", :selected => "false"} %>
        </li>
        <li class="nav-item">
          <%= link_to "javascript:void(0)", :class => "nav-link disabled" do %>
            &nbsp;&nbsp;&nbsp;&nbsp;<i class="fas fa-long-arrow-alt-right"></i>&nbsp;&nbsp;&nbsp;&nbsp;
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "LIVRAISON", "javascript:void(0)", id: "shipping", :class => "nav-link disabled", :data => {:toggle => "tab"}, :role =>'tab', :aria => {:controls => "shipping", :selected => "false"} %>
        </li>
      </ul>
    </div>
    <div class="tab-content">
      <div class="card-body tab-pane fade show active" id="cart" role="tabpanel" aria-labelledby="cart">
        <%= render 'cart', carts: @carts, total: @amount %>
      </div>
      <div class="card-body tab-pane fade" id="shipping" role="tabpanel" aria-labelledby="shipping">
        <%= render 'shipping', total: @amount, user: current_user, order: @order %>
      </div>
      <div class="card-body tab-pane fade" id="payment" role="tabpanel" aria-labelledby="payment">
        pay
      </div>
    </div>
  </div>
</div>

<script>
    $(function() {
        let toggleNavBar = document.querySelectorAll(".main-nav-pills li a");
        let toggleContent = document.querySelectorAll(".tab-content .card-body");
        let buttonToChange2 = document.querySelectorAll(".btn.btn-sm.btn-outline-secondary")[1];
        
        let btnShipping = document.getElementById("btn_shipping");
        let btnPayment = document.getElementById("btn_payment");

        console.log(toggleContent[0]);
        console.log(toggleContent[1]);
        console.log(toggleContent[2]);

        btnShipping.addEventListener("click", changetoShipping);
        function changetoShipping() {
            toggleNavBar[0].classList.remove("active");
            toggleNavBar[2].classList.add("active");
            toggleContent[0].classList.remove("show", "active");
            toggleContent[1].classList.add("show", "active");
        };
    });
</script>

app/views/carts/new.html.erb
<h1>Nouveau Panier</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Retour', carts_path %>

app/views/carts/payment.html.erb
<% 
  order =  Order.find_by_stripe_id(params[:stripeToken])
  linked_cart = Cart.where(order_id: order.id)
  amount = linked_cart.map(&:total_per_item).instance_eval { reduce(:+) } 
%>

<!-- Main Content -->
<div class="container my-3">
  <div class="card">
    <div class="card-body">
      <div class="text-center py-3">
      	<%= image_tag("check.svg", :style => "width:48px;height:48px;") %>
        <h1>Merci.</h1>
        <p>Votre commande est prise en compte et sera traitée le plus tôt possible.</p>
        <p class="mb-0">
          <span class="text-muted">Numéro de commande : </span>
          <span class="text-info">#ORD<%= order.id %></span>
        </p>
        <p>
          <span class="text-muted">Montant : </span>
          <span class="text-info">€ <%= sprintf( "%0.02f", amount) %></span>
        </p>
        <p>Un email de confirmation a été envoyé à l'adresse : <u><%= User.find(order.user_id).email %></u></p>
        <%= link_to "Continuer les achats", variants_path, class: "btn btn-primary rounded mb-3" %>
        <%= link_to "Voir la commande", order_path(order), class: "btn btn-outline-secondary rounded mb-3" %>
      </div>
    </div>
  </div>
</div>
<!-- /Main Content -->