config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'home#home'
  
  resources :variants, :path => "produits" do 
    resources :reviews
  end
  resources :wishlists, :path => "ma_wishlist"

  resources :orders, :path => "mes_commandes"
  resources :items
  resources :options
  resources :option_values
  resources :option_associations

  resources :searches, :path => "recherches"
  
  devise_for :users,
    controllers: { registrations: 'registrations' },
    path: '',
    path_names: { sign_up: 'creer_un_compte', sign_in: 'identification', sign_out: 'deconnexion', password: 'mot_de_passe_oublie'}
  devise_scope :user do 
    get "/mon_profil" => "registrations#show"
  end
  
  get '/carts/payment' => 'carts#payment'
  resources :carts, :path => "mon_panier"
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'
  resources :posts, :path => "blog"
  get "/postDashboard", to: "posts#postDashboard"

  get '/home/about_us', to: 'home#about_us', as: 'a_propos'
  get "/home/contact", to: "home#contact", as: 'contact'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
	belongs_to :author, class_name: "User"
	
  has_many :reviews
  has_many :variants

  has_many :tag_items, as: :taggable
  has_many :tags, through: :tag_items, as: :taggable

  has_one_attached :image_item

  validates :title,
    presence: true, 
    length: { minimum: 2, maximum: 30 }
  validates :description,
    presence: true, 
    length: { minimum: 20, maximum: 200 }

  def review_average
	  rating = 0
	  if not Review.where(item_id: self.id).empty?
	    rating = Review.where(item_id: self.id).map(&:rating).instance_eval { reduce(:+) / size.to_f }
	  end 
	  return rating
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create, :update, :edit, :destroy]

  def index
    @items = Item.page(params[:page]).per(30)
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    varantsofitem = Variant.where(item_id: @item.id)
    varantsofitem.each do |element|
      element.destroy
    end
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :category_id, :image_item)
    end
    def check_admin
      if RoleAssignation.find_by_user_id(current_user.id).role_id == 4 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8
      else
        respond_to do |format|
          format.html { redirect_to request.referer }
          format.json { head :no_content }
        end
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="container">

  <%= form_with(model: Review.new, local: true) do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> erreurs ont empeché ce produit d'être sauvegardé:</h2>

        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <table class="table table-striped">
      <tbody>

      <tr>
        <th scope="row"><%= form.label :Nom %></th>
        <td class="d-flex justify-content-center"><%= form.text_field :title %></td>
      </tr>

      <tr>
        <th scope="row"><%= form.label :Description %></th>
        <td class="d-flex justify-content-center"><%= form.text_area :description, class: "w-50" %></td>
      </tr>

      <tr>
        <th scope="row"><%= form.label :"Catégorie" %></th>
        <td class="d-flex justify-content-center"><%= form.collection_select(:category_id, Category.all, :id, :name) %></td>
      </tr>

      <tr>
          <th scope="row"><%= form.label :Image %></th>
          <td class="d-flex justify-content-center"><%= form.file_field :image_item %></td>
      </tr>

      </tbody>
    </table>

    <div class="d-flex justify-content-center mb-3">
      <%= submit_tag("Créer/Mettre à jour une option", :class=>"btn btn-success") %>
    </div>

  <% end %>

</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Détail', @item %> |
<%= link_to 'Retour', items_path %>

app/views/items/index.html.erb
<p id="notice" class="text-success container"><%= notice %></p>


<div class="container">
  <h1>Produits</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Titre</th>
        <th>Description</th>
        <th>Catégorie</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td class="align-middle"><%= item.title %></td>
          <td class="align-middle"><%= item.description[0..20] %>...</td>
          <td class="align-middle"><%= item.category.name %></td>
          <td><%= link_to 'Details', item, class: "btn btn-primary" %></td>
          <td><%= link_to 'Modifier', edit_item_path(item), class: "btn btn-warning" %></td>
          <td><%= link_to 'Supprimer', item, method: :delete, data: { confirm: 'Etes-vous sûr?' }, class: "btn btn-danger" %></td>
       
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  

  <div class="row mb-3">
    <%= link_to 'Nouvel item', new_item_path, class: "btn btn-success align-middle mr-3" %>
    <%= link_to "Deconnexion", destroy_user_session_path, :class => "btn btn-style-6 btn-danger align-middle", :data => { :method => "delete"} %>
  </div>

</div>


<!-- Pagination -->
  <div class="d-flex justify-content-center">
    <%= paginate @items, window: 3 %>
  </div>
<!-- /Pagination -->

app/views/items/new.html.erb
<h1>Nouvel Item</h1>

<%= render 'form', item: @item %>

<%= link_to "Revenir à l'index", items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container mt-3 mb-3">
  <div class="card">
    <div class="card-body">

    <table class="table table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Catégorie</th>
      </tr>
    </thead>
    <tbody>
    
        <tr>
          <td class="align-middle"><%= @item.title %></td>
          <td class="align-middle"><%= @item.description %></td>
          <td class="align-middle"><%= @item.category.name %></td>
        </tr>
    </tbody>
  </table>

        <strong>Variantes :</strong>
       

            <table class="table table-striped">
            <thead>
              <tr>
                <th>Nom</th>
                <th>Prix</th>
                <th>Stock</th>
                <th colspan="3">Actions</th>
              </tr>
          </thead>
            <% Variant.where(item_id: @item.id).each do |variant|%>

            <tbody>
                <tr>
                  <td class="align-middle"><%= variant.title %></td>
                  <td class="align-middle"><%= variant.price %> €</td>
                  <td class="align-middle"><%= variant.stock %></td>
                  <td><%= link_to 'Détail', variant, class: "btn btn-primary" %></td>
                  <td><%= link_to 'Modifier', edit_variant_path(variant), class: "btn btn-warning" %></td>
                  <td><%= link_to 'Supprimer', variant, method: :delete, data: { confirm: 'Etes-vous sûr?' }, class: "btn btn-danger" %></td>
                </tr>
            </tbody>
            <% end %>
          </table>
          

      </div>

      <div class="d-flex justify-content-around mb-3"><%= form_for Variant.new do |f| %>
        <%= f.hidden_field :item_id, :value => @item.id, class: "btn btn-success" %>
          <button type="submit" class="btn btn-success">Ajouter une nouvelle variante</button>
      <% end %>
      </div>
      
      <div class="d-flex justify-content-around mb-3">
        <%= link_to "Revenir à l'index", items_path, class: "btn btn-primary"%>
        <%= link_to "Mettre à jour l'item", edit_item_path(@item), class: "btn btn-warning" %> 
        <%= link_to 'Supprimer', @item, method: :delete, data: { confirm: 'Etes-vous sûr?' }, class: "btn btn-danger" %>
      </div>
      
      
      

</div>