config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'home#home'
  
  resources :variants, :path => "produits" do 
    resources :reviews
  end
  resources :wishlists, :path => "ma_wishlist"

  resources :orders, :path => "mes_commandes"
  resources :items
  resources :options
  resources :option_values
  resources :option_associations

  resources :searches, :path => "recherches"
  
  devise_for :users,
    controllers: { registrations: 'registrations' },
    path: '',
    path_names: { sign_up: 'creer_un_compte', sign_in: 'identification', sign_out: 'deconnexion', password: 'mot_de_passe_oublie'}
  devise_scope :user do 
    get "/mon_profil" => "registrations#show"
  end
  
  get '/carts/payment' => 'carts#payment'
  resources :carts, :path => "mon_panier"
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'
  resources :posts, :path => "blog"
  get "/postDashboard", to: "posts#postDashboard"

  get '/home/about_us', to: 'home#about_us', as: 'a_propos'
  get "/home/contact", to: "home#contact", as: 'contact'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :theme
	
  has_many :likes
  has_many :comments, as: :commentable
  has_many :tag_items, as: :taggable
  has_many :tags, through: :tag_items, as: :taggable
	
  validates :title,
    presence: true, 
    length: { minimum: 2, maximum: 50 }
  validates :content,
    presence: true, 
    length: { minimum: 20, maximum: 2000 }
  
  paginates_per 6

  has_one_attached :image_post

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create, :update, :edit, :destroy]

  def index
    @posts = Post.page(params[:page])
  end

  def postDashboard
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :theme_id, :image_post)
  end

  def check_admin
    if RoleAssignation.find_by_user_id(current_user.id).role_id == 3 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8
    else
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.json { head :no_content }
      end
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
<h1>Créer un nouvel article</h1>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> a empeché cette post d'être sauvegardée:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row"><%= form.label :"Theme de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.collection_select(:theme_id, Theme.all, :id, :name) %></td>
    </tr>

    <tr>
      <th scope="row"><%= form.label :"Titre de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.text_field :title %></td>
    </tr>

    <tr>
      <th scope="row"><%= form.label :"Contenu de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.text_area(:content, size: '50x10') %></td>
    </tr>
    <tr>
      <th scope="row"><%= form.label :Image %></th>
      <td class="d-flex justify-content-center"><%= form.file_field :image_post %></td>
    </tr>
  </tbody>
</table>

<div class="d-flex justify-content-center mb-3">
  <%= submit_tag("Ajouter l'article", :class=>"btn btn-success") %>
</div>
 <% end %>
<div>

app/views/posts/_formEdit.html.erb
<div class="container">
<h1>Post Edition</h1>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> a empeché cette post d'être sauvegardée:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row"><%= form.label :"Theme de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.collection_select(:theme_id, Theme.all, :id, :name) %></td>
    </tr>

    <tr>
      <th scope="row"><%= form.label :"Titre de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.text_field :title %></td>
    </tr>

    <tr>
      <th scope="row"><%= form.label :"Contenu de l'article: " %></th>
      <td class="d-flex justify-content-center"><%= form.text_area(:content, size: '50x10') %></td>
    </tr>

    <tr>
      <th scope="row"><%= form.label :Image %></th>
      <td class="d-flex justify-content-center"><%= form.file_field :image_variant %></td>
    </tr>
    
  </tbody>
</table>

<div class="d-flex justify-content-center mb-3">
  <%= submit_tag("Modifier l'article", :class=>"btn btn-success") %>
</div>
 <% end %>
<div>

app/views/posts/_gridPost.html.erb
<div class="card card-blog">
  <%= link_to post_path(post.id), class: "zoom-hover" do %>
    <% if post.image_post.attached? %>
      <%= image_tag(post.image_post, alt: post.title, :height => '290') %>
    <% else %>
      <% $pix = ["https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-craft-920393-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pottery-3023901-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-yarn-1325766-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-sew-3490492-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pitcher-2320354-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-china-1515579-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-shell-921124-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-embroidery-3524900-960-720.jpg"]%>
      <%= image_tag($pix.sample, :size => '440x290') %>
    <% end %>
  <% end %>
  <div class="card-body">
    <%= link_to elements.title, post_path(post.id), class: "title h4" %>
    <span><%= elements.content[0..25] %>...</span>
  </div>
    <div class="card-footer flex-center">
      <div class="small text-muted counter">
        <i class="far fa-heart"></i> 55
        <i class="far fa-comment-dots ml-3"></i> 15
      </div>
      <%= link_to "> Read more", post_path(post.id), class: "bold" %>
    </div>
</div>

app/views/posts/_listPost.html.erb
<div class="card card-blog card-blog-list mt-3" visible>
  <%= link_to post_path(post.id), class: "zoom-hover" do %>
    <% if post.image_post.attached? %>
      <%= image_tag(post.image_post, alt: post.title, :height => '290') %>
    <% else %>
      <% $pix = ["https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-craft-920393-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pottery-3023901-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-yarn-1325766-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-sew-3490492-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pitcher-2320354-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-china-1515579-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-shell-921124-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-embroidery-3524900-960-720.jpg"]%>
      <%= image_tag($pix.sample, :size => '440x290') %>
    <% end %>
  <% end %>
  <div class="card-body">
  	<%= link_to elements.title, post_path(post.id), class: "title h4" %>
    <p class="d-none d-sm-block"><%= elements.content[0..25] %>...   
    	<%= link_to "> Continuer a lire", post_path(post.id) %>
    </p>
    <div class="small text-muted counter">
      <i class="fas fa-thumbs-up"></i> 55
      <i class="far fa-comment"></i> 15
    </div>
  </div>
</div>

app/views/posts/_popularTags.html.erb
<%= link_to "Fashion", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Design", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Beauty", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Travel", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Sport", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Active tag", "javascript:void(0)", class: "btn btn-light rounded-pill active" %>
<%= link_to "Cooking", "javascript:void(0)", class: "btn btn-light rounded-pill" %>
<%= link_to "Technology", "javascript:void(0)", class: "btn btn-light rounded-pill" %>

app/views/posts/_postSideBar.html.erb
<div class="card-body">
  <div class="row">
    <div class="col-12 col-sm-6 col-md-12">
      <div class="card card-blog shadow-none">
        <%= link_to posts_path, class: "zoom-hover" do %>
          <img src="https://image.noelshack.com/fichiers/2019/11/3/1552473977-ceramics-clay-handmade-22823.jpg" alt="Blog">
        <% end %>
        <div class="card-body p-0 text-center">
          <%= link_to "", posts_path, class: "title h5 mt-3" %>
          <div class="small text-muted">
            <i class="far fa-heart"></i> 55 Likes
            <i class="far fa-comment-dots ml-3"></i> 15 Comments
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_postsComments.html.erb
<div class="media my-4">
  <%= link_to image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;"), "javascript:void(0)" %>
  <div class="media-body ml-2 ml-sm-3">
    <textarea rows="2" placeholder="Leave a comment" class="form-control border autosize"></textarea>
    <button class="btn btn-sm btn-light border border-top-0 btn-block">Post</button>
  </div>
</div>
<div class="media">
  <%= link_to image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;"), "javascript:void(0)" %>
  <div class="media-body ml-2 ml-sm-3">
    <div class="d-flex flex-wrap">
      <%= link_to "Auteur", "javascript:void(0)", class: "mr-2" %>
      <span class="text-muted">17 minutes ago</span>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et suscipit vitae eius incidunt odit nulla, repellat harum, repudiandae doloremque expedita.</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <%= link_to "javascript:void(0)", class: "text-muted", title: "vote positif" do %>
          5 <i class="fas fa-chevron-up"></i></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to "javascript:void(0)", class: "text-muted", title: "vote négatif" do %>
          <i class="fas fa-chevron-down"></i></i>
        <% end %>
      </li>
      <li class="list-inline-item"><%= link_to "Répondre", "javascript:void(0)", class: "text-muted" %></li>
    </ul>
    <hr>
       
    <div class="media">
      <%= link_to image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;"), "javascript:void(0)" %>
      <div class="media-body ml-2 ml-sm-3">
        <div class="d-flex flex-wrap">
          <%= link_to "Répondeur wesh", "javascript:void(0)", class: "mr-2" %>
          <span class="text-muted">5 minutes ago</span>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et suscipit vitae eius incidunt odit nulla, repellat harum, repudiandae doloremque expedita.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= link_to "javascript:void(0)", class: "text-muted", title: "vote positif" do %>
              <i class="fas fa-chevron-up"></i></i>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to "javascript:void(0)", class: "text-muted", title: "vote négatif" do %>
              <i class="fas fa-chevron-down"></i></i>
            <% end %>
          </li>
          <li class="list-inline-item"><%= link_to "Répondre", "javascript:void(0)", class: "text-muted" %></li>
        </ul>
        <hr>
      </div>
    </div>
  </div>
</div>

<div class="media">
  <%= link_to image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;"), "javascript:void(0)" %>
  <div class="media-body ml-2 ml-sm-3">
    <div class="d-flex flex-wrap">
      <%= link_to "Autre auteur", "javascript:void(0)", class: "mr-2" %>
      <span class="text-muted">il y a une heure</span>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et suscipit vitae eius incidunt odit nulla, repellat harum, repudiandae doloremque expedita.</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <%= link_to "javascript:void(0)", class: "text-muted", title: "vote positif" do %>
          <i class="fas fa-chevron-up"></i></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to "javascript:void(0)", class: "text-muted", title: "vote négatif" do %>
          <i class="fas fa-chevron-down"></i></i>
        <% end %>
      </li>
      <li class="list-inline-item"><%= link_to "Répondre", "javascript:void(0)", class: "text-muted" %></li>
    </ul>
    <hr>
  </div>
</div>

app/views/posts/edit.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= render 'formEdit', post: @post %>

<div class="container mb-3">
<%= link_to 'Retour', posts_path, class: "btn btn-warning" %>
</div>

app/views/posts/index.html.erb
<!-- Main Content -->
<div class="container my-3">
  <div class="col">
      <div class="jumbotron jumbotron-fluid ego">
        <div class="container">
          <h1 class="display">Nativea est fier de vous présenter ses talents !</h1>
          <h3>Un article par artisan pour découvrir</h3>
          <h3>son savoir-faire.</h3>
        </div>
      </div>
  <div class="row">
    <div class="col">
      
      <!-- Blog Toolbar -->
      <div class="card">
        <div class="card-body d-flex justify-content-end align-items-center py-2">
          <span class="mr-auto bold">Derniers articles</span>
          <div class="dropdown dropdown-hover">
            <button class="btn btn-light btn-sm border rounded-pill dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Ordre <i class="fas fa-chevron-down"></i></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right shadow-sm">
              <button class="dropdown-item" type="button">Nouveaux</button>
              <button class="dropdown-item" type="button">Anciens</button>
            </div>
          </div>
          <%= link_to "javascript:void(0)", class: "btn btn-icon rounded-pill btn-sm btn-primary ml-3 post_grid_layout", :data => {:toggle => "tooltip"} do %>
            <i class="fas fa-th-large"></i>
          <% end %>
          <%= link_to "javascript:void(0)", class: "btn btn-icon rounded-pill btn-sm btn-outline-primary ml-1 post_list_layout", :data => {:toggle => "tooltip"} do %>
            <i class="fas fa-th-list"></i>
          <% end %>
        </div>
      </div>
      <!-- /Blog Toolbar -->
      
      <!-- Blog Grid -->
      <div class="card-deck card-deck-2-columns mt-3" id="grid-layout">
        <% @posts.order("created_at DESC").each do |grElements|%>
         <%=render 'gridPost', elements: grElements, post: Post.find(grElements.id) %>
        <% end %>
      </div>           
      <!-- /Blog Grid -->
      
      <!-- Blog List -->
      <div id="list-layout" hidden>
        <% @posts.order("created_at DESC").each do |liElements|%>
          <%= render 'listPost', elements: liElements, post: Post.find(liElements.id)%>
        <% end %>
      </div>
      <!-- /Blog List -->
      
      <!-- Pagination -->
        <div class="d-flex justify-content-center">
          <%= paginate @posts, window: 2 %>
        </div>
      <!-- /Pagination -->
    </div>

    <!-- Blog Sidebar -->
    <div class="col-md-4 col-lg-4 mt-3 mt-md-0">
      <div class="card">
        <div class="card-header bg-white border-bottom bold roboto-condensed">
          <h5 class="bold mb-0">LES PLUS <span class="text-primary">COMMENTÉS</span></h5>
        </div>
        <!--RenderSideBar-->
          <% i = 0 %>
            <% while i < 2 do %>
              <%= render 'postSideBar' %>
            <% i += 1 %>
          <% end %>
        <!--/RenderSideBar-->
    </div>
      <div class="card mt-3">
        <div class="card-header bg-white border-bottom bold roboto-condensed">
          <h5 class="bold mb-0">TAG <span class="text-primary">POPULAIRES</span></h5>
        </div>
        <div class="card-body">
          <div class="btn-group-scatter">
            <!--RenderPopularTags-->
              <%= render 'popularTags' %>
            <!--/RenderPopularTags-->
          </div>
        </div>
      </div>
    </div>
    <!-- /Blog Sidebar -->

  </div>
</div>
<!-- /Main Content -->
<script>
   $(function () {
     $('.post_list_layout').click(function (event) {
       $('#grid-layout').attr('hidden', true);
       $('#list-layout').attr('hidden', false);
       $('.post_list_layout').removeClass('btn-outline-primary').addClass('btn-primary');
       $('.post_grid_layout').removeClass('btn-primary').addClass('btn-outline-primary');
       event.preventDefault();
     })
     $('.post_grid_layout').click(function (event) {
       $('#grid-layout').attr('hidden', false);
       $('#list-layout').attr('hidden', true);
       $('.post_grid_layout').removeClass('btn-outline-primary').addClass('btn-primary');
       $('.post_list_layout').removeClass('btn-primary').addClass('btn-outline-primary');
       event.preventDefault();
     })
   })
</script>

app/views/posts/new.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= render 'form', post: @post %>

<div class="container mb-3">
<%= link_to 'Retour', posts_path, class: "btn btn-warning" %>
</div>

app/views/posts/postDashboard.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<p id="notice" class="text-success container"><%= notice %></p>

<div class="container mb-3">
<%= link_to 'Retour', posts_path, class: "btn btn-warning" %>
</div>
<div class="container">
  <h1>Modifier un article</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Titre</th>
        <th>Description</th>
        <th>Categorie</th>
        <th colspan="3"></th>
        <th><%= link_to 'Nouveau Post', new_post_path, class: "btn btn-success align-middle mr-3" %></th>
      </tr>
    </thead>
    <tbody>

      <% @posts.each do |post| %>
        <tr>
          <td class="align-middle"><%= post.title %></td>
          <td class="align-middle"><%= post.content[0..30] %>...</td>
          <td><%= link_to 'Détail', post, class: "btn btn-primary" %></td>
          <td><%= link_to 'Modifier', edit_post_path(post), class: "btn btn-warning" %></td>
          <td><%= link_to 'Supprimer', post, method: :delete, data: { confirm: 'Etes-vous sûr?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="row mb-3">
    <%= link_to "Déconnexion", destroy_user_session_path, :class => "btn btn-style-6 btn-danger align-middle", :data => {:method => "delete"} %>
  </div>
</div>

app/views/posts/show.html.erb
<!-- Main Content -->
<div class="container my-3">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body" lang="zxx">
          <!-- Blog Info -->
          <ul class="list-inline">
            <li class="list-inline-item"><small><i class="fas fa-clock"></i> Jan 01, 18</small></li>
            <li class="list-inline-item"><small><i class="fas fa-user"></i><%= link_to "Admin", "javascript:void(0)", class: "text-muted" %></small></li>
            <li class="list-inline-item"><small><i class="fas fa-tag"></i><%= link_to "Fashion", "javascript:void(0)", class: "text-muted" %></small></li>
          </ul>

          <!-- Blog Content -->
          <h2 class="bold"><%= @post.title %></h2>
          
          <% if @post.image_post.attached? %>
            <%= image_tag(@post.image_post, alt: @post.title, :class => 'img-fluid my-3') %>
          <% else %>
            <% $pix = ["https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-craft-920393-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pottery-3023901-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-yarn-1325766-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-sew-3490492-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pitcher-2320354-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-china-1515579-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-shell-921124-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-embroidery-3524900-960-720.jpg"]%>
            <%= image_tag($pix.sample, :class => 'img-fluid my-3') %>
          <% end %>

          <%= @post.content %>
          <!-- /Blog Content -->

          <hr>

          <!-- Blog Comments -->
          <h3>Comments</h3>
          <%= render 'postsComments' %>
          <!-- /Blog Comments -->
        </div>
      </div>
    </div>

      <!-- Blog Sidebar -->
      <div class="col-md-4 col-lg-4 mt-3 mt-md-0">
        <div class="card">
          <div class="card-header bg-white border-bottom bold roboto-condensed">
            <h5 class="bold mb-0">LES PLUS <span class="text-primary">COMMENTÉS</span></h5>
          </div>
          <!--RenderSideBar-->
          <% i = 0 %>
            <% while i < 2 do %>
              <%= render 'postSideBar' %>
            <% i += 1 %>
          <% end %>
          <!--/RenderSideBar-->

        <div class="card mt-3">
          <div class="card-header bg-white border-bottom bold roboto-condensed">
            <h5 class="bold mb-0">TAG <span class="text-primary">POPULAIRES</span></h5>
          </div>
          <div class="card-body">
            <div class="btn-group-scatter">
              <!--RenderPopularTags-->
                <%= render 'popularTags' %>
              <!--/RenderPopularTags-->

            </div>
          </div>
        </div>
      </div>
      <!-- /Blog Sidebar -->
    </div>
  </div>
</div>
<!-- /Main Content -->