config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'home#home'
  
  resources :variants, :path => "produits" do 
    resources :reviews
  end
  resources :wishlists, :path => "ma_wishlist"

  resources :orders, :path => "mes_commandes"
  resources :items
  resources :options
  resources :option_values
  resources :option_associations

  resources :searches, :path => "recherches"
  
  devise_for :users,
    controllers: { registrations: 'registrations' },
    path: '',
    path_names: { sign_up: 'creer_un_compte', sign_in: 'identification', sign_out: 'deconnexion', password: 'mot_de_passe_oublie'}
  devise_scope :user do 
    get "/mon_profil" => "registrations#show"
  end
  
  get '/carts/payment' => 'carts#payment'
  resources :carts, :path => "mon_panier"
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'
  resources :posts, :path => "blog"
  get "/postDashboard", to: "posts#postDashboard"

  get '/home/about_us', to: 'home#about_us', as: 'a_propos'
  get "/home/contact", to: "home#contact", as: 'contact'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
  <div class="footer w-100 collapse">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-sm-6 col-lg-4 text-center px-3 mb-5">
          <h5 class="bold">SOUSCRIRE</h5>
          <p>et profitez <strong class="text-primary">10% de réduction</strong></p>
          <form>
            <div class="form-group">
              <input type="email" class="form-control rounded-pill text-center" placeholder="Saisissez votre email">
            </div>
            <button type="button" class="btn btn-primary btn-block rounded-pill">Souscrire</button>
          </form>
        </div>
        <div class="col-6 col-lg-2 d-none d-sm-block">
        </div>
        <div class="col-6 col-lg-3 d-none d-sm-block">
          <h6 class="bold">Service client</h6>
          <div class="list-group list-group-flush list-group-no-border list-group-sm">
            <%= link_to "Aide", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Comment acheter ?", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Livraison", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Retourner un article ?", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Méthodes de paiement", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Modalités de livraison", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
          </div>
        </div>
        <div class="col-6 col-lg-3 d-none d-sm-block">
          <h6 class="bold">Nativea</h6>
          <div class="list-group list-group-flush list-group-no-border list-group-sm">
            <%= link_to "A propos", a_propos_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "Termes et Conditions", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Politique de confidentialité", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "FAQ", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Notre histoire", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
            <%= link_to "Services", "javascript:void(0)", class: "list-group-item list-group-item-action" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright pt-3 collapse" >
    <div>Copyright © 2019 Nativea - All right reserved</div>
    <div>Réalisé avec <i class="fas fa-heart"></i> par les kittens</div>
  </div>


<!-- /Footer -->

app/views/layouts/_header.html.erb
<!--Header -->
<header>
  <div class="container">

  <!-- Sidebar toggler -->
  <%= link_to "javascript:void(0)", :class => "nav-link nav-icon ml-ni nav-toggler mr-3 d-flex d-lg-none", :data => {:toggle => "modal", :target => "#menuModal"} do %>
    <i class="fas fa-bars"></i>
  <% end %>

    <!-- Logo -->
    <%= link_to variants_path, class: "nav-link nav-logo" do %>
      <strong>NATIVEA</strong>
    <% end %>

    <!-- Main navigation -->
    <ul class="nav nav-main ml-auto d-none d-lg-flex"> <!-- hidden on md -->
      <li class="nav-item"><%= link_to "Accueil", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Magasin", variants_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Blog", posts_path, class: "nav-link" %></li>
      <li class="nav-item dropdown dropdown-hover">
      <%= link_to a_propos_path, :class => "nav-link dropdown-toggle forwardable", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
        Nous <i class="fas fa-chevron-down"></i>
      <% end %>
      <div class="dropdown-menu">        
          <%= link_to "A propos", a_propos_path, class: "dropdown-item" %>
          <%= link_to "Contact", contact_path, class: "dropdown-item" %>
      </div>
      
      <% if user_signed_in? && RoleAssignation.find_by_user_id(current_user.id).role_id > 2 %>
        <li class="nav-item dropdown dropdown-hover">
          <%= link_to "javascript:void(0)", :class => "nav-link dropdown-toggle forwardable", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
            Dashboard <i class="fas fa-chevron-down"></i>
          <% end %>
          <% if RoleAssignation.find_by_user_id(current_user.id).role_id == 4 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8 %>
            <div class="dropdown-menu">
              <%= link_to "Créer un Variant", new_variant_path, class: "dropdown-item" %>
              <%= link_to "Liste des Options", options_path, class: "dropdown-item" %>
              <%= link_to "Créer une Option", new_option_path, class: "dropdown-item" %>
              <%= link_to "Liste des OptionValue", option_values_path, class: "dropdown-item" %>
              <%= link_to "Créer une OptionValue", new_option_value_path, class: "dropdown-item" %>
              <%= link_to "Liste des OptionAssociation", option_associations_path, class: "dropdown-item" %>
              <%= link_to "Créer une OptionAssociation", new_option_association_path, class: "dropdown-item" %>
            </div>
          <% elsif RoleAssignation.find_by_user_id(current_user.id).role_id == 3 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8 %>
            <div class="dropdown-menu">
              <%= link_to "Créer un Post", new_post_path, class: "dropdown-item" %>
            </div>
          <% else %>
            <div class="dropdown-menu">Pas de dashboard disponible</div>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item dropdown dropdown-hover">
        <ul class="nav ml-auto">
          <li class="nav-item dropdown dropdown-hover">
            <% if user_signed_in? %>
              <%= link_to "mon_profil_path", :class => "nav-link dropdown-toggle pr-0", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
                <i class="fas fa-user"></i> Bonjour <%= current_user.firstname %>  <i class="fas fa-chevron-down"></i>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="media p-2 align-items-center mb-2">
                  <div class="mr-2 size50x50">
                    <% if current_user.avatar.attached? %>
                      <%= image_tag current_user.avatar, alt: current_user.fullname, :class => "img-thumbnail rounded-circle" %>
                    <% elsif current_user.gender == "Homme" %>
                      <%= image_tag ("mister.jpg"), alt: current_user.fullname, :class => "img-thumbnail rounded-circle" %>
                    <% else %>
                      <%= image_tag ("miss.jpg"), alt: current_user.fullname, :class => "img-thumbnail rounded-circle" %>
                    <% end %>
                  </div>
                  <div class="media-body">
                    <strong><%= current_user.fullname %></strong>
                    <div class="small"><%= current_user.email%></div>
                  </div>
                </div>
                <%= link_to carts_path, :class => "dropdown-item has-icon has-badge" do %>
                  <i class="fas fa-shopping-cart"></i>&nbsp;&nbsp;Panier <span class="badge rounded badge-primary"><%= Cart.where(user_id: current_user.id).where(order_id: nil).length %></span>
                <% end %>  
                <%= link_to wishlists_path, :class => "dropdown-item has-icon has-badge" do %>
                  <i class="fas fa-heart"></i>&nbsp;&nbsp;Wishlist <span class="badge rounded badge-primary"><%= Wishlist.where(user_id:current_user.id).length %></span>
                <% end %>      
                <%= link_to mon_profil_path, :class => "dropdown-item has-icon" do %>
                  <i class="fas fa-cogs"></i>&nbsp;&nbsp;Mon Compte
                <% end %>    
                <div class="dropdown-divider"></div>
                <%= link_to destroy_user_session_path, :class => "dropdown-item has-icon text-danger", :data => {:method => "delete"}, :role =>'tab' do %>
                  <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Déconnexion</a>
                <% end %> 
              </div>
            <% else %>
              <%= link_to "javascript:void(0)", :class => "nav-link dropdown-toggle pr-0", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
                <i class="fas fa-user"></i> Bonjour visiteur  <i class="fas fa-chevron-down"></i>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="media p-2 align-items-center mb-2">
                  <div class="media-body">
                    <%= link_to "Connexion", new_user_session_path, class: "btn btn-primary btn-sm btn-block" %>
                    <p class="text-sm text-muted mt-3 mb-0"><%= link_to "Créer un compte", new_user_registration_path %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <!-- /Main navigation -->
      
    <% if user_signed_in? %>
      <%
        carts = Cart.where(user_id: current_user.id).where(order_id: nil).order(:id)
        carts.empty? ? countCart = 0 : countCart = carts.size 
        amount = carts.map(&:total_per_item).instance_eval { reduce(:+) }
      %>
      <ul class="nav ml-auto ml-sm-0">
        <!-- Cart dropdown -->
        <li class="nav-item dropdown dropdown-hover dropdown-cart">
          <%= link_to carts_path, :class => "nav-link nav-icon mr-nis dropdown-toggle forwardable ml-2", :data => {:toggle => "dropdown"}, :role =>'button', :aria => {:haspopup => "true", :expanded => "false"} do %>
            <i class="fas fa-shopping-cart"></i>
            <span class="badge badge-primary"><%= countCart %></span>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right">
            <% if countCart != 0 %>
              <% carts.each do |cart_item| %>
                <div class="media">
                  <%
                    variant = Variant.find(cart_item.variant_id)
                    item = Item.find(variant.item_id)
                  %>
                  <% if variant.image_variant.attached? %>
                    <%= link_to image_tag(variant.image_variant, alt: variant.title, height: "50"), variant_path(variant.id), class: "navbar-brand mr-1"  %>
                  <% else %>
                    <% $pix = ["https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-craft-920393-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pottery-3023901-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-yarn-1325766-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-clogs-968486-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-sew-3490492-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-pitcher-2320354-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-china-1515579-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-shell-921124-960-720.jpg", "https://image.noelshack.com/fichiers/2019/12/5/1553285219-embroidery-3524900-960-720.jpg"]%>
                    <%= link_to image_tag($pix.sample, height: "50"), variant_path(variant.id), class: "navbar-brand mr-1" %>
                  <% end %>
                  <div class="media-body">
                    <%= link_to variant.title, variant_path(variant.id), title: variant.title %>
                    <span class="qty"><%= cart_item.quantity %></span> x <span class="price">€ <%= variant.price %></span>
                    <%= link_to cart_path(cart_item.id), :class => "close", :data => {:confirm => "Etes-vous sûr ?", :method => "delete"}, :rel => "nofollow" do %>
                      <span class="remove-product"><i class="far fa-times-circle"></i></span>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <div class="d-flex justify-content-between pb-3 pt-2">
                <span>Total</span>
                <strong>€ <%= sprintf( "%0.02f", amount) %></strong>
              </div>
              <div class="d-flex justify-content-between pb-2">
                <div class="w-100 mr-1">
                  <%= link_to "Consulter le Panier / Payer", carts_path, class: "btn btn-block rounded-pill btn-primary" %>
                </div>
              </div>
            <% else %>
              No item in the cart
            <% end %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</header>
<!-- /Header -->

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
  	<%= link_to "×", "javascript:void(0)",class: "close", :data => {:dismiss => "alert"} %>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

<script>
	$(function () {
	  setTimeout(function(){
	    $('#flash').remove();
	  }, 5000);
	});
</script>

app/views/layouts/_modalmenu.html.erb
<!--Menu Modal -->
  <div class="modal modal-left modal-menu" id="menuModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header shadow">
          <%= link_to variants_path, class: "h5 mb-0 d-flex align-items-center" do %>
            <strong>NATIVEA</strong>
          <% end %>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body shadow">
          <ul class="menu" id="menu">
            <li class="no-sub">
              <%= link_to root_path do %>
                <i class="fas fa-home"></i> Accueil
              <% end %>
            </li>
            <li>
              <%= link_to variants_path do %>
                <i class="fas fa-store"></i> Magasin
              <% end %>
            </li>
            <li>
              <%= link_to posts_path do %>
                <i class="fas fa-pen-square"></i> Blog
              <% end %>
            </li>
            <li>
              <%= link_to "javascript:void(0)", :class => "has-arrow" do %>
                <i class="fas fa-user"></i> Mon Compte
              <% end %>
              <ul>
                <% if user_signed_in? %>
                  <li>
                    <%= link_to mon_profil_path, class: "dropdown-item" do %>
                      <i class="fas fa-cogs"></i> Profil
                    <% end %>
                  </li>
                  <li>
                    <%= link_to carts_path, class: "dropdown-item" do %>
                      <i class="fas fa-shopping-cart"></i> Panier
                    <% end %>
                  </li>
                  <li>
                    <%= link_to wishlists_path, class: "dropdown-item" do %>
                      <i class="fas fa-heart"></i> Wishlist
                    <% end %>
                  </li>
                  <li><%= link_to "Déconnexion", destroy_user_session_path, :class => "dropdown-item text-danger", :data => {:method => "delete"} %></li>
                <% else %>
                  <li><%= link_to "Créer un compte", new_user_registration_path %></li>
                  <li><%= link_to "Connexion", new_user_session_path %></li>
                <% end %>
              </ul>
            </li>
            <% if user_signed_in? && RoleAssignation.find_by_user_id(current_user.id).role_id > 2 %>
              <li class="nav-item dropdown dropdown-hover">
                <%= link_to "javascript:void(0)", :class => "has-arrow" do %>
                  Dashboard
                <% end %>
                <ul>
                  <% if RoleAssignation.find_by_user_id(current_user.id).role_id == 4 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8 %>
                    <li><%= link_to "Créer un Variant", new_variant_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Liste des Options", options_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Créer une Option", new_option_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Liste des OptionValue", option_values_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Créer une OptionValue", new_option_value_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Liste des OptionAssociation", option_associations_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Créer une OptionAssociation", new_option_association_path, class: "dropdown-item" %></li>
                  <% elsif RoleAssignation.find_by_user_id(current_user.id).role_id == 3 or RoleAssignation.find_by_user_id(current_user.id).role_id == 8 %>
                    <li><%= link_to "Créer un Post", new_post_path, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- /Menu Modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nativea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '587187048417050',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.2'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>




  <%= render 'layouts/header' %>
  <div id="flash">
    <%= render 'layouts/messages' %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= render 'layouts/modalmenu' %>
  
  </body>
 </html>